let data=[];let gateways=[];let analytics={};const $=x=>document.getElementById(x);const money=x=>`€${Number(x).toFixed(0)}`;const clamp=(x,min=0,max=100)=>Math.max(min,Math.min(max,x));
function render(){
  let searchEl=$("search");
  let q=searchEl?searchEl.value.toLowerCase():"";
  let rowsEl=$("rows");
  if(rowsEl){
    let a=data.filter(r=>r.gateway_id.toLowerCase().includes(q)||r.name.toLowerCase().includes(q));
    rowsEl.innerHTML=a.map(r=>`<tr><td><b>${r.gateway_id}</b><br><small>${r.name}</small></td><td>${r.risk_score.toFixed(1)}</td><td><span class="badge ${r.priority}">${r.priority}</span></td><td>${r.confidence}</td><td>${money(r.estimated_avoidable_cost)}</td><td class="${r.decision==="VISIT"?"visit":"monitor"}">${r.decision}</td><td><button class="view" onclick="show('${r.gateway_id}')">View</button></td></tr>`).join("");
  }
  let totalEl=$("total"); if(totalEl){ totalEl.textContent=data.length; }
  let highEl=$("high"); if(highEl){ highEl.textContent=data.filter(r=>["HIGH","CRITICAL"].includes(r.priority)).length; }
  let visitsEl=$("visits"); if(visitsEl){ visitsEl.textContent=data.filter(r=>r.decision==="VISIT").length; }
  let exposureEl=$("exposure"); if(exposureEl){ exposureEl.textContent=money(data.reduce((s,r)=>s+r.estimated_avoidable_cost,0)); }
  let barsEl=$("bars"); if(barsEl){
    let gs=["LOW","MEDIUM","HIGH","CRITICAL"];
    barsEl.innerHTML=gs.map(g=>{let n=data.filter(r=>r.priority===g).length,p=data.length?n/data.length*100:0;return `<div class="barrow"><b>${g}</b><div class="bar"><div class="fill" style="width:${p}%"></div></div><span>${n}</span></div>`}).join("");
  }
}
function renderGateways(){if(!gateways.length)return;let rowsEl=$("gateway-rows");if(!rowsEl)return;rowsEl.innerHTML=gateways.map(g=>`<tr><td><b>${g.gateway_id}</b><br><small>${g.name}</small></td><td>${g.failure_rate}</td><td>${g.incidents_30d}</td><td>${g.downtime_hours_30d}</td><td>${g.days_since_last_incident}</td><td><span class="badge ${g.status}">${g.status}</span></td></tr>`).join("")} 
function renderAnalytics(){if(!analytics || !Object.keys(analytics).length)return;let el=$("analytics-summary");if(!el)return;el.innerHTML=`<div class="metric-box"><span>Total Gateways</span><b>${analytics.total_gateways}</b></div><div class="metric-box"><span>Healthy</span><b>${analytics.healthy}</b></div><div class="metric-box"><span>Warning</span><b>${analytics.warning}</b></div><div class="metric-box"><span>Degraded</span><b>${analytics.degraded}</b></div><div class="metric-box"><span>High/Critical</span><b>${analytics.high_or_critical}</b></div><div class="metric-box"><span>Visits</span><b>${analytics.visit_recommended}</b></div><div class="metric-box"><span>Avg Risk</span><b>${analytics.average_risk_score}</b></div><div class="metric-box"><span>Weekly Exposure</span><b>${money(analytics.total_weekly_exposure)}</b></div>`}
function calculateRiskFromValues(values){const failure=clamp(Number(values.failureRate||0),0,100);const incidents=Number(values.incidents||0);const downtime=Number(values.downtime||0);const recency=Number(values.recency||0);const score=Number((clamp(failure*0.40 + ((incidents/10)*100)*0.25 + ((downtime/100)*100)*0.20 + (((30-recency)/30)*100)*0.15,0,100)).toFixed(2));const priority=score>=80?"CRITICAL":score>=60?"HIGH":score>=30?"MEDIUM":"LOW";const visitCost=380;const brokenCost=priority==="HIGH"||priority==="CRITICAL"?600:0;const decision=brokenCost>visitCost?"VISIT":"MONITOR";const reasons=[];if(failure>=15)reasons.push("Failure rate is elevated.");if(incidents>=5)reasons.push("Repeated incidents occurred in the last 30 days.");if(downtime>=40)reasons.push("Downtime is significant.");if(recency<=7)reasons.push("A recent incident increases priority.");if(brokenCost>visitCost)reasons.push("One week of recurring cost exceeds the visit cost.");if(!reasons.length)reasons.push("Current indicators do not cross the visit threshold.");const confidence=reasons.length>=3?"HIGH":reasons.length===2?"MEDIUM":"LOW";return {score,priority,decision,confidence,reasons};}
function updateManualResult(){const resultBox=$("manual-result");if(!resultBox)return;const values={failureRate:$("failure-rate").value,incidents:$("incidents").value,downtime:$("downtime").value,recency:$("recency").value};const result=calculateRiskFromValues(values);$("manual-score").textContent=result.score.toFixed(2);$("manual-priority").textContent=result.priority;$("manual-decision").textContent=result.decision;$("manual-confidence").textContent=result.confidence;$("manual-reasons").innerHTML=result.reasons.map(x=>`<li>${x}</li>`).join("");resultBox.classList.remove("hidden");}
function loadDemoValues(){const values={failureRate:18.5,incidents:7,downtime:58,recency:3};$("failure-rate").value=values.failureRate;$("incidents").value=values.incidents;$("downtime").value=values.downtime;$("recency").value=values.recency;updateManualResult();}
function updateSelectedGatewayResult(){const resultBox=$("selected-result");if(!resultBox)return;const values={failureRate:$("detail-failure-rate").value,incidents:$("detail-incidents").value,downtime:$("detail-downtime").value,recency:$("detail-recency").value};const result=calculateRiskFromValues(values);$("selected-score").textContent=result.score.toFixed(2);$("selected-priority").textContent=result.priority;$("selected-decision").textContent=result.decision;$("selected-confidence").textContent=result.confidence;$("selected-reasons").innerHTML=result.reasons.map(x=>`<li>${x}</li>`).join("");resultBox.classList.remove("hidden");}
function loadSelectedDemoValues(){const values={failureRate:18.5,incidents:7,downtime:58,recency:3};$("gateway-name").value="Gateway A";$("gateway-id").value="GW-001";$("detail-failure-rate").value=values.failureRate;$("detail-incidents").value=values.incidents;$("detail-downtime").value=values.downtime;$("detail-recency").value=values.recency;updateSelectedGatewayResult();}
async function load(){try{let r=await fetch("/api/recommendations");if(!r.ok)throw 0;data=await r.json();render();let g=await fetch("/api/gateways");if(g.ok)gateways=await g.json();renderGateways();let a=await fetch("/api/analytics/summary");if(a.ok){analytics=await a.json();renderAnalytics();}}catch(e){let msg=$("msg");if(msg){msg.textContent="API is not running. Start with python run.py";msg.classList.remove("hidden");}}}
async function recalc(){try{let recalcBtn=$("recalc");if(recalcBtn){recalcBtn.disabled=true;recalcBtn.textContent="Calculating...";}let r=await fetch("/api/recommendations/run",{method:"POST"});if(!r.ok)throw 0;data=(await r.json()).recommendations;render();let g=await fetch("/api/gateways");if(g.ok)gateways=await g.json();renderGateways();let a=await fetch("/api/analytics/summary");if(a.ok){analytics=await a.json();renderAnalytics();}}catch(e){let msg=$("msg");if(msg){msg.textContent="Recalculation failed";msg.classList.remove("hidden");}}finally{let recalcBtn=$("recalc");if(recalcBtn){recalcBtn.disabled=false;recalcBtn.textContent="Recalculate";}}}
window.show=id=>{let r=data.find(x=>x.gateway_id===id);if(!r)return;let titleEl=$("title");if(titleEl){titleEl.textContent=`${r.gateway_id} — ${r.name}`;}$("score").textContent=r.risk_score.toFixed(1);$("priority").textContent=r.priority;$("decision").textContent=r.decision;$("confidence").textContent=r.confidence;$("reasons").innerHTML=r.reasons.map(x=>`<li>${x}</li>`).join("");let detail=$("detail");if(detail){detail.classList.remove("hidden");detail.scrollIntoView({behavior:"smooth"})}};
let searchEl=$("search");if(searchEl){searchEl.addEventListener("input",render);}let recalcBtn=$("recalc");if(recalcBtn){recalcBtn.addEventListener("click",recalc);}let closeBtn=$("close");if(closeBtn){closeBtn.addEventListener("click",()=>{let detail=$("detail");if(detail){detail.classList.add("hidden");}});}let calculateBtn=$("calculate-risk");if(calculateBtn){calculateBtn.addEventListener("click",updateManualResult);}let demoBtn=$("load-demo");if(demoBtn){demoBtn.addEventListener("click",loadDemoValues);}let selectedCalcBtn=$("recalculate-selected");if(selectedCalcBtn){selectedCalcBtn.addEventListener("click",updateSelectedGatewayResult);}let selectedDemoBtn=$("load-selected-demo");if(selectedDemoBtn){selectedDemoBtn.addEventListener("click",loadSelectedDemoValues);}load();
